[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
; upload_port = /dev/cu.usbmodem1101
upload_port = /dev/cu.usbmodem2101

; Required libraries for OLED display
lib_deps = 
    adafruit/Adafruit SH110X@^2.1.10
    adafruit/Adafruit GFX Library@^1.11.9
    ricmoo/QRCode@^0.0.1
    olikraus/U8g2@^2.36.12

; Optional: Enable better debugging
build_type = debug
monitor_filters = esp32_exception_decoder